"""change trip date time columns

Revision ID: e046f2e8b130
Revises: c6a0de9863c0
Create Date: 2026-09-21 21:29:49.103052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e046f2e8b130'
down_revision: Union[str, Sequence[str], None] = 'c6a0de9863c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'loading_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('trip', 'loading_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('trip', 'unloading_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('trip', 'unloading_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'unloading_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('trip', 'unloading_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('trip', 'loading_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('trip', 'loading_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
