"""initial migration

Revision ID: f47b47c32aa7
Revises: 
Create Date: 2026-09-13 20:36:22.509605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47b47c32aa7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bhada_no', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(), nullable=False),
    sa.Column('to_location', sa.String(), nullable=False),
    sa.Column('loading_date', sa.DateTime(), nullable=True),
    sa.Column('loading_time', sa.DateTime(), nullable=True),
    sa.Column('unloading_date', sa.DateTime(), nullable=True),
    sa.Column('unloading_time', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('real_weight', sa.Float(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('real_size', sa.String(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('final_rate', sa.Integer(), nullable=True),
    sa.Column('party_advance', sa.Integer(), nullable=True),
    sa.Column('party_balance', sa.Integer(), nullable=True),
    sa.Column('driver_advance', sa.Integer(), nullable=True),
    sa.Column('khali_bhatta', sa.Integer(), nullable=True),
    sa.Column('load_bhatta', sa.Integer(), nullable=True),
    sa.Column('toll', sa.Integer(), nullable=True),
    sa.Column('disel_liter', sa.Float(), nullable=True),
    sa.Column('disel_amount', sa.Integer(), nullable=True),
    sa.Column('driver_bachat', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Integer(), nullable=True),
    sa.Column('empty_toll', sa.Integer(), nullable=True),
    sa.Column('empty_disel', sa.Integer(), nullable=True),
    sa.Column('parking', sa.Integer(), nullable=True),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bhada_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('driver')
    # ### end Alembic commands ###
