from sqlalchemy import Column,String,Integer,DateTime,Float,func,Date,Time
from app.database.session import Base

class Trip(Base):
    __tablename__ = "trip"
    id = Column(Integer,primary_key=True)
    bhada_no = Column(Integer,nullable=False,unique=True)
    from_location = Column(String,nullable=False)
    to_location = Column(String,nullable=False)
    loading_date = Column(Date)
    loading_time = Column(Time)
    unloading_date = Column(Date)
    unloading_time = Column(Time)
    weight = Column(Float)
    real_weight = Column(Float)
    size = Column(String)
    real_size = Column(String)
    rate = Column(Integer)
    final_rate = Column(Integer)
    party_advance = Column(Integer)
    party_balance = Column(Integer)
    driver_advance = Column(Integer)
    khali_bhatta = Column(Integer)
    load_bhatta = Column(Integer)
    toll = Column(Integer)
    disel_liter = Column(Float)
    disel_amount = Column(Integer)
    driver_bachat = Column(Integer)
    commission = Column(Integer)
    empty_toll = Column(Integer)
    empty_disel = Column(Integer)
    parking = Column(Integer)
    broker_name = Column(String)
    created_at = Column(DateTime(timezone=True),server_default=func.now(),nullable=False)
    updated_at = Column(DateTime(timezone=True),server_default=func.now(),nullable=False,onupdate=func.now())
